
＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2021-01-27 14:28:01,147                                   
【执行时间】[43496]毫秒                                   
【错误位置】System.String 属性[(null)]                                   
【错误描述】出现未知异常                                   
【错误详情】
System.NullReferenceException: Object reference not set to an instance of an object.
   at WeChat.Core.Common.WeChat.SendMessage.GetToken() in F:\ERP_Code\WeChat.Core.Api\src\WeChat.Core.Common\WeChat\SendMessageHelper\SendMessage.cs:line 153
   at WeChat.Core.Common.WeChat.SendMessage.Submitted(String openId, String name, String mobile) in F:\ERP_Code\WeChat.Core.Api\src\WeChat.Core.Common\WeChat\SendMessageHelper\SendMessage.cs:line 124
   at WeChat.Core.Api.Controllers.WeChatAPIController.SendMessage(SendMessageModel model) in F:\ERP_Code\WeChat.Core.Api\src\WeChat.Core.Api\Controllers\WeChatAPIController.cs:line 229
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
